 # This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: "Chicago" }, { name: "Copenhagen" }])
#   Mayor.create(name: "Emanuel", city: cities.first)
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})



adventureone = Adventure.create({name: "Empire State Building Express 102" ,location: "ChIJtcaxrqlZwokRfwmmibzPsTU", price_per_person: true,per_person: 85, price_event: 0, timeframe: 120, hints: "Held a world record for nearly 40 years"})
adventuretwo = Adventure.create({name: "Empire State Building Express 86" ,location: "ChIJtcaxrqlZwokRfwmmibzPsTU", price_per_person: true,per_person: 65, price_event: 0, timeframe: 120, hints: "A NY icon"})
adventurethree = Adventure.create({name: "Empire State Building Express GA" ,location: "ChIJtcaxrqlZwokRfwmmibzPsTU", price_per_person: true,per_person: 32, price_event: 0, timeframe: 180, hints: "Only 2 acres but has it's own zip code"})
adventurefour = Adventure.create({name: "Freedom tower" ,location: "ChIJ-4MbiBlawokR5ixJ4E8Km5c", price_per_person: false,per_person:  0, price_event: 0, timeframe: 60, hints: "Freedom tower"})
adventurefive = Adventure.create({name: "Freedom tower Observatory" ,location: "ChIJ-4MbiBlawokR5ixJ4E8Km5c", price_per_person: true ,per_person: 32, price_event: 0, timeframe: 120, hints: "'See Forever'"})
adventuresix = Adventure.create({name: "Strawberry fields",location: "ChIJlRYp-4xYwokRqtwtQBYVz80", price_per_person: false,per_person:  0, price_event: 0, timeframe: 60, hints: "'Imagine all the people'"})
adventureseven = Adventure.create({name: "Times Square" ,location: "ChIJmQJIxlVYwokRLgeuocVOGVU", price_per_person: false,per_person:  0, price_event: 0, timeframe: 60, hints: "'The crossroads of the world'"})
adventureeight = Adventure.create({name: "Brooklyn bridge" ,location: "ChIJK3vOQyNawokRXEa9errdJiU", price_per_person: false,per_person:  0, price_event: 0, timeframe: 120, hints: "An icon of this city"})
adventurenine = Adventure.create({name: "Smorgasburg" ,location: "ChIJ65rH6TBawokRUuhYOuefE28", price_per_person: false,per_person:  0, price_event: 0, timeframe: 180, hints: "Hungry?"})
adventureten= Adventure.create({name: "Escape the Room Downtown" ,location: "ChIJYZrvCIFZwokRW3Xf3V0BWnU", price_per_person: true,per_person:  0, price_event: 28, timeframe: 120, hints: "Escape the Room Downtown"})
adventureeleven = Adventure.create({name: "Escape the Room Midtown" ,location: "ChIJHW8b6qhZwokRJtwCEu3NV3w", price_per_person: true,per_person:  0, price_event: 28, timeframe: 120, hints: "Escape the Room Midtown"})
adventuretwelve = Adventure.create({name: "High Line" ,location: "ChIJ5bQPhMdZwokRkTwKhVxhP1g", price_per_person: false,per_person:  0, price_event: 0, timeframe: 60, hints: "Look up."})
Adventure.create({name: "Top of The Rock" ,location: "ChIJNZvR1v5YwokRFHSjCAPwtIs", price_per_person: true,per_person: 0, price_event: 30, timeframe: 120, hints: "You might run into Liz Lemon"})
Adventure.create({name: "Chelsea Driving Range Simulator" ,location: "ChIJ9QDTS7pZwokRJCPIsMF2Kiw", price_per_person: false,per_person:  0, price_event: 45, timeframe: 60, hints: "Fooorrrrrrrrrre!"})
Adventure.create({name: "Crocodile lounge" ,location: "ChIJaQ2FO55ZwokRKYAlmF0IlzA", price_per_person: true, per_person: 20, price_event: 0, timeframe: 120, hints: "Not alligator, but..."})
Adventure.create({name: "Momofuko noodle bar" ,location: "ChIJkXQ3_INZwokRE74ZvG46Jjc", price_per_person: true,per_person: 175, price_event: 0, timeframe: 150, hints: "Best noodles in town"})
Adventure.create({name: "Sleep no more" ,location: "ChIJFTweVbZZwokRNkSu_ncOwJs", price_per_person: true,per_person: 0, price_event: 85, timeframe: 120, hints: "Otherwise known as 'insomnia'"})
Adventure.create({name: "MOMA" ,location: "ChIJKxDbe_lYwokRVf__s8CPn-o", price_per_person: true,per_person: 25, price_event: 0, timeframe: 180, hints: "Home of the greats"})
Adventure.create({name: "American Museum of Natural History" ,location: "ChIJCXoPsPRYwokRsV1MYnKBfaI", price_per_person: true,per_person: 25, price_event: 0, timeframe: 180, hints: "Their motto is 'To discover and interpret'"})
Adventure.create({name: "Guggenheim" ,location: "ChIJmZ5emqJYwokRuDz79o0coAQ", price_per_person: true ,per_person: 25 , price_event: 0, timeframe: 180, hints: "'Temple of the Spirit'"})
Adventure.create({name: "The Cloisters" ,location: "ChIJK6bycAH0wokRrSnflfrnkZE", price_per_person: true ,per_person: 25 , price_event: 0, timeframe: 180, hints: "Let's get midieval!"})
Adventure.create({name: "New York Botanical Garden" ,location: "ChIJuz7Sf3nzwokRwmoqtEc51q8", price_per_person: true ,per_person: 20 , price_event: 0, timeframe: 180, hints: ""})
Adventure.create({name: "The Met" ,location: "ChIJb8Jg9pZYwokR-qHGtvSkLzs", price_per_person: true,per_person: 25, price_event: 0, timeframe: 140, hints: "The largest in the U.S."})
Adventure.create({name: "Museum of Sex" ,location: "ChIJR026QqZZwokRgLuHSIZNIKM", price_per_person: true,per_person:  18, price_event: 0, timeframe: 120, hints: "Very taboo"})
Adventure.create({name: "Grand Central Terminal" ,location: "ChIJa1QZIAJZwokRySwnNKYyMno", price_per_person: false,per_person:  0, price_event: 0 , timeframe: 60, hints: "A starry night... inside."})
Adventure.create({name: "New York Public Library" ,location: "ChIJqaiomQBZwokR6XvzjGAIes8", price_per_person: false,per_person: 0 , price_event: 0, timeframe: 60, hints: "The original google"})
Adventure.create({name: "Ikea Ferry" ,location: "ChIJgQSshBxawokRCo9bnnXvGaI", price_per_person: true,per_person: 5 , price_event: 0, timeframe: 180, hints: "Blue and gold"})
Adventure.create({name: "Chelsea Market" ,location: "ChIJw2lMFL9ZwokRosAtly52YX4", price_per_person: false ,per_person:  0, price_event: 0, timeframe: 60, hints: "An historic city block of vendors"})
Adventure.create({name: "Washington Square Park" ,location: "ChIJjX494pBZwokRGH620d9eYfo", price_per_person: false ,per_person:  0, price_event: 0, timeframe: 60, hints: "Recognized by its 'square-arch'"})
Adventure.create({name: "Roosevelt Island Tram" ,location: "ChIJN9PkFOZYwokRNV1xIL9GXyQ", price_per_person: true ,per_person:  3, price_event: 0, timeframe: 120, hints: "The best way to cross half of a river"})
Adventure.create({name: "St. Patrick's Cathedral" ,location: "ChIJR1W5DfxYwokR2n7Oo1xhEbA", price_per_person: false ,per_person:  0, price_event: 0 , timeframe: 120, hints: "Dedicated to the most famous patron saint"})
Adventure.create({name: "Brooklyn Brewery" ,location: "ChIJUaAuMl1ZwokRt0-S_ynnRtc", price_per_person: true,per_person:  10, price_event: 0, timeframe: 160, hints: "A Brooklyn staple since '87"})
Adventure.create({name: "Eataly Rooftop" ,location: "ChIJdUc5EaRZwokRTmwOW-Qrv8Y", price_per_person: true,per_person:  20, price_event: 0, timeframe: 120, hints: "An italian view"})
Adventure.create({name: "Upright Citizen's Brigade" ,location: "ChIJQ6i29oJZwokRxl2zvEPIc0w", price_per_person: true,per_person: 10, price_event: 0, timeframe: 90, hints: "Upright Citizen's Brigade"})
Adventure.create({name: "Madame Tussauds" ,location: "ChIJ8VOfr1RYwokRhil9_pcMKuc", price_per_person: true,per_person: 30 , price_event: 0, timeframe: 120, hints: "Let's wax nostalgic"})
Adventure.create({name: "Statue of Liberty" ,location: "ChIJPTacEpBQwokRKwIlDXelxkA", price_per_person: true,per_person: 18 , price_event: 0, timeframe: 180, hints: "This lady was a gift"})
Adventure.create({name: "Kenka" ,location: "ChIJiRfje5xZwokR474atxPrCwE", price_per_person: true,per_person:  25, price_event: 0, timeframe: 120, hints: "Stay for the dessert surprise"})
Adventure.create({name: "Hall of Science" ,location: "ChIJG2aZ1wT2wokRzz-VKP0lkJg", price_per_person: false,per_person:  0, price_event: 0, timeframe: 90, hints: "'Peace through understanding'"})
Adventure.create({name: "Charging Bull" ,location: "ChIJURWoF5pYwokRIfXv4To528c", price_per_person: false,per_person:  0, price_event: 0, timeframe: 60, hints: "3 ton guerilla art"})
Adventure.create({name: "5 bar Karaoke Lounge" ,location: "ChIJEyBg56hZwokRQp-JzPC9AOI", price_per_person: false,per_person:  0, price_event: 80, timeframe: 60, hints: "A stripper pole is their finishing touch"})
Adventure.create({name: "Raines Law Room" ,location: "ChIJ8wOZzaJZwokR6impURvzUbE", price_per_person: true,per_person: 40 , price_event: 0, timeframe: 120, hints: "Ring the bell and pull the lamp string"})
Adventure.create({name: "The Garret" ,location: "ChIJkdFGdJNZwokRY_FA1UjcHGI", price_per_person: false,per_person: 30, price_event: 0, timeframe: 120 , hints: "Head to the back of Five guys"})
Adventure.create({name: "Beauty and Essex" ,location: "ChIJJWCTb4FZwokRLe7HgJSuHFI", price_per_person: true,per_person:  30, price_event:  0, timeframe: 120, hints: "Go past the junk"})
Adventure.create({name: "Mulberry Project" ,location: "ChIJGaAyS4hZwokRzKiuS8sNU0A", price_per_person: true,per_person: 30 , price_event: 0, timeframe: 120, hints: "Behind the red door"})
Adventure.create({name: "Bar Centrale" ,location: "ChIJ4e2I9lNYwokRaO-Ake7hsak", price_per_person: true,per_person:  30, price_event: 0, timeframe: 120 , hints: "324"})
Adventure.create({name: "Attaboy" ,location: "ChIJxUZzBIdZwokRWA8buz-Nktc", price_per_person: true,per_person:  30, price_event: 0, timeframe: 120, hints: "134"})
Adventure.create({name: "Bathtub Gin" ,location: "ChIJcTnRKLlZwokRT8ZXt9W9cgw", price_per_person: true,per_person: 30 , price_event: 0, timeframe: 120, hints: "Behind Stone Street Coffee"})
Adventure.create({name: "Apotheke" ,location: "ChIJNxEu8SZawokRARkMLjXhyBY", price_per_person: true ,per_person: 30 , price_event: 0, timeframe: 120, hints: "The Chemist"})
Adventure.create({name: "Little Branch" ,location: "ChIJjY7y6ZJZwokRXF5CA_X4l-I", price_per_person: true ,per_person: 30 , price_event: 0, timeframe: 120, hints: "Talk to the man on the corner"})
Adventure.create({name: "Old Rabbit Club" ,location: "ChIJsU0rhJFZwokRmUJmeDamSLo", price_per_person: true ,per_person:  30, price_event: 0, timeframe: 120, hints: "Follow the yellow rabbit"})
Adventure.create({name: "Morbid Anatomy Museum" ,location: "ChIJRRCONVRawokRUHEzv2hWkus", price_per_person: true ,per_person:  8, price_event: 0, timeframe: 120, hints: "American Horror Story in NY"})
Adventure.create({name: "Wave Hill" ,location: "ChIJC21UnrXzwokRn8wMoHqA8tw", price_per_person: true ,per_person:  8, price_event: 0, timeframe:160 , hints: "Exploring the human connection to the natural world"})
Adventure.create({name: "Central Park Zoo" ,location: "ChIJaWjW_PFYwokRFD8a2YQu12U", price_per_person: true,per_person:  18, price_event: 0, timeframe: 120, hints: "The first menagerie in NY"})
Adventure.create({name: "Black Ant" ,location: "ChIJeXX3pYRZwokR-xjPszfpGm4", price_per_person: true,per_person:  20, price_event: 0, timeframe: 190, hints: "Bug food?"})
Adventure.create({name: "La Caverna" ,location: "ChIJ2z3KFIFZwokRpLxbFwFRMLM", price_per_person: true,per_person:  30, price_event: 0, timeframe: 180, hints: "Cave dwelling"})
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
# Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})


matt = User.create({name: "Matt", email: "Matt@wingit.com", password: "password"})
sam = User.create({name: "Sam", email: "Sam@wingit.com", password: "password"})
ethan = User.create({name: "Ethan", email: "Ethan@wingit.com", password: "password"})
david = User.create({name: "David", email: "David@wingit.com", password: "password"})

Prev_Adventure.create({user_id: matt.id, adventure_id: adventureone.id})
Prev_Adventure.create({user_id: matt.id, adventure_id: adventuretwo.id})
Prev_Adventure.create({user_id: matt.id, adventure_id: adventurethree.id})
Prev_Adventure.create({user_id: sam.id, adventure_id: adventurefour.id})
Prev_Adventure.create({user_id: sam.id, adventure_id: adventurefive.id})
Prev_Adventure.create({user_id: sam.id, adventure_id: adventuresix.id})
Prev_Adventure.create({user_id: ethan.id, adventure_id: adventureseven.id})
Prev_Adventure.create({user_id: ethan.id, adventure_id: adventureeight.id})
Prev_Adventure.create({user_id: ethan.id, adventure_id: adventurenine.id})
Prev_Adventure.create({user_id: david.id, adventure_id: adventureten.id})
Prev_Adventure.create({user_id: david.id, adventure_id: adventureeleven.id})
Prev_Adventure.create({user_id: david.id, adventure_id: adventuretwelve.id})







