# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: "Chicago" }, { name: "Copenhagen" }])
#   Mayor.create(name: "Emanuel", city: cities.first)
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})



Adventure.create({name: "Empire State Building Express 102" ,location: "ChIJtcaxrqlZwokRfwmmibzPsTU", price_per_person: true,per_person: 85, price_event: 0, timeframe: 120, hints: "Empire State Building"})
Adventure.create({name: "Empire State Building Express 86" ,location: "ChIJtcaxrqlZwokRfwmmibzPsTU", price_per_person: true,per_person: 65, price_event: 0, timeframe: 120, hints: "Empire State Building"})
Adventure.create({name: "Empire State Building Express GA" ,location: "ChIJtcaxrqlZwokRfwmmibzPsTU", price_per_person: true,per_person: 32, price_event: 0, timeframe: 180, hints: "Empire State Building"})
Adventure.create({name: "Freedom tower" ,location: "ChIJ-4MbiBlawokR5ixJ4E8Km5c", price_per_person: false,per_person:  0, price_event: 0, timeframe: 60, hints: "Freedom tower"})
Adventure.create({name: "Freedom tower Observatory" ,location: "ChIJ-4MbiBlawokR5ixJ4E8Km5c", price_per_person: true ,per_person: 32, price_event: 0, timeframe: 120, hints: "Freedom tower Observatory"})
Adventure.create({name: "Strawberry fields",location: "ChIJlRYp-4xYwokRqtwtQBYVz80", price_per_person: false,per_person:  0, price_event: 0, timeframe: 60, hints: "Strawberry fields"})
Adventure.create({name: "Times Square" ,location: "ChIJmQJIxlVYwokRLgeuocVOGVU", price_per_person: false,per_person:  0, price_event: 0, timeframe: 60, hints: "Times Square"})
Adventure.create({name: "Brooklyn bridge" ,location: "ChIJK3vOQyNawokRXEa9errdJiU", price_per_person: false,per_person:  0, price_event: 0, timeframe: 120, hints: "Brooklyn bridge"})
Adventure.create({name: "Smorgasburg" ,location: "ChIJ65rH6TBawokRUuhYOuefE28", price_per_person: false,per_person:  0, price_event: 0, timeframe: 180, hints: "Smorgasburg"})
Adventure.create({name: "Escape the Room Downtown" ,location: "ChIJYZrvCIFZwokRW3Xf3V0BWnU", price_per_person: true,per_person:  0, price_event: 28, timeframe: 120, hints: "Escape the Room Downtown"})
Adventure.create({name: "Escape the Room Midtown" ,location: "ChIJHW8b6qhZwokRJtwCEu3NV3w", price_per_person: true,per_person:  0, price_event: 28, timeframe: 120, hints: "Escape the Room Midtown"})
Adventure.create({name: "High Line" ,location: "ChIJ5bQPhMdZwokRkTwKhVxhP1g", price_per_person: false,per_person:  0, price_event: 0, timeframe: 60, hints: "High Line"})
Adventure.create({name: "Top of The Rock" ,location: "ChIJNZvR1v5YwokRFHSjCAPwtIs", price_per_person: true,per_person:  , price_event: 30, timeframe: 120, hints: "Top of The Rock"})
Adventure.create({name: "Chelsea Driving Range Simulator" ,location: "ChIJ9QDTS7pZwokRJCPIsMF2Kiw", price_per_person: false,per_person:  0, price_event: 45, timeframe: 60, hints: "Chelsea Driving Range Simulator"})
Adventure.create({name: "Crocodile lounge" ,location: "ChIJaQ2FO55ZwokRKYAlmF0IlzA", price_per_person: true, per_person: 20, price_event: 0, timeframe: 120, hints: "Crocodile lounge"})
Adventure.create({name: "Momofuko noodle bar" ,location: "ChIJkXQ3_INZwokRE74ZvG46Jjc", price_per_person: true,per_person: 175, price_event: 0, timeframe: 150, hints: "Momofuko noodle bar"})
Adventure.create({name: "Sleep no more" ,location: "ChIJFTweVbZZwokRNkSu_ncOwJs", price_per_person: true,per_person: 0, price_event: 85, timeframe: 120, hints: "Sleep no more"})
Adventure.create({name: "MOMA" ,location: "ChIJKxDbe_lYwokRVf__s8CPn-o", price_per_person: true,per_person: 25, price_event: , timeframe: 180, hints: "MoMa"})
Adventure.create({name: "American Museum of Natural History" ,location: "ChIJCXoPsPRYwokRsV1MYnKBfaI", price_per_person: true,per_person: 25, price_event: 0, timeframe: 180, hints: "American Museum of Natural History"})
Adventure.create({name: "Guggenheim" ,location: "ChIJmZ5emqJYwokRuDz79o0coAQ", price_per_person: true ,per_person: 25 , price_event: 0, timeframe: 180, hints: "Guggenheim"})
Adventure.create({name: "The Cloisters" ,location: "ChIJK6bycAH0wokRrSnflfrnkZE", price_per_person: true ,per_person: 25 , price_event: 0, timeframe: 180, hints: "The Cloisters"})
Adventure.create({name: "New York Botanical Garden" ,location: "ChIJuz7Sf3nzwokRwmoqtEc51q8", price_per_person: true ,per_person: 20 , price_event: 0, timeframe: 180, hints: "New York Botanical Garden"})
Adventure.create({name: "The Met" ,location: "ChIJb8Jg9pZYwokR-qHGtvSkLzs", price_per_person: true,per_person: 25, price_event: 0, timeframe: 140, hints: "The Met"})
Adventure.create({name: "Museum of Sex" ,location: "ChIJR026QqZZwokRgLuHSIZNIKM", price_per_person: true,per_person:  18, price_event: 0, timeframe: 120, hints: "Museum of Sex"})
Adventure.create({name: "Grand Central Terminal" ,location: "ChIJa1QZIAJZwokRySwnNKYyMno", price_per_person: false,per_person:  0, price_event: 0 , timeframe: 60, hints: "Grand Central Terminal"})
Adventure.create({name: "New York Public Library" ,location: "ChIJqaiomQBZwokR6XvzjGAIes8", price_per_person: false,per_person: 0 , price_event: 0, timeframe: 60, hints: "Public Library"})
Adventure.create({name: "Ikea Ferry" ,location: "ChIJgQSshBxawokRCo9bnnXvGaI", price_per_person: true,per_person: 5 , price_event: 0, timeframe: 180, hints: "Ikea ferry"})
Adventure.create({name: "Chelsea Market" ,location: "ChIJw2lMFL9ZwokRosAtly52YX4", price_per_person: false ,per_person:  0, price_event: 0, timeframe: 60, hints: "Chelsea Market"})
Adventure.create({name: "Washington Square Park" ,location: "ChIJjX494pBZwokRGH620d9eYfo", price_per_person: false ,per_person:  0, price_event: 0, timeframe: 60, hints: "Washington Square Park"})
Adventure.create({name: "Roosevelt Island Tram" ,location: "ChIJN9PkFOZYwokRNV1xIL9GXyQ", price_per_person: true ,per_person:  3, price_event: 0, timeframe: 120, hints: "Roosevelt Island Tram"})
Adventure.create({name: "St. Patrick's Cathedral" ,location: "ChIJR1W5DfxYwokR2n7Oo1xhEbA", price_per_person: false ,per_person:  0, price_event: 0 , timeframe: 120, hints: "St. Patrick's Cathedral"})
Adventure.create({name: "Brooklyn Brewery" ,location: "ChIJUaAuMl1ZwokRt0-S_ynnRtc", price_per_person: true,per_person:  10, price_event: 0, timeframe: 160, hints: "Brooklyn Brewery"})
Adventure.create({name: "Eataly Rooftop" ,location: "ChIJdUc5EaRZwokRTmwOW-Qrv8Y", price_per_person: true,per_person:  20, price_event: 0, timeframe: 120, hints: "Eataly Rooftop"})
Adventure.create({name: "Upright Citizen's Brigade" ,location: "ChIJQ6i29oJZwokRxl2zvEPIc0w", price_per_person: true,per_person: 10, price_event: 0, timeframe: 90, hints: "Upright Citizen's Brigade"})
Adventure.create({name: "Madame Tussauds" ,location: "ChIJ8VOfr1RYwokRhil9_pcMKuc", price_per_person: true,per_person: 30 , price_event: 0, timeframe: 120, hints: "Madame Tussauds"})
Adventure.create({name: "Statue of Liberty" ,location: "ChIJPTacEpBQwokRKwIlDXelxkA", price_per_person: true,per_person: 18 , price_event: 0, timeframe: 180, hints: "Statue of Liberty"})
Adventure.create({name: "Kenka" ,location: "ChIJiRfje5xZwokR474atxPrCwE", price_per_person: true,per_person:  25, price_event: 0, timeframe: 120, hints: "Kenka"})
Adventure.create({name: "Hall of Science" ,location: "ChIJG2aZ1wT2wokRzz-VKP0lkJg", price_per_person: false,per_person:  0, price_event: 0, timeframe: 90, hints: "Hall of Science"})
Adventure.create({name: "Charging Bull" ,location: "ChIJURWoF5pYwokRIfXv4To528c", price_per_person: false,per_person:  0, price_event: 0, timeframe: 60, hints: "Charging Bull"})
Adventure.create({name: "5 bar Karaoke Lounge" ,location: "ChIJEyBg56hZwokRQp-JzPC9AOI", price_per_person: false,per_person:  0, price_event: 80, timeframe: 60, hints: "5 bar Karaoke Lounge"})
Adventure.create({name: "Raines Law Room" ,location: "ChIJ8wOZzaJZwokR6impURvzUbE", price_per_person: true,per_person: 40 , price_event: 0, timeframe: 120, hints: "Ring the bell and pull the lamp string"})
Adventure.create({name: "The Garret" ,location: "ChIJkdFGdJNZwokRY_FA1UjcHGI", price_per_person: false,per_person: 30, price_event: 0, timeframe: 120 , hints: "Head to the back of Five guys"})
Adventure.create({name: "Beauty and Essex" ,location: "ChIJJWCTb4FZwokRLe7HgJSuHFI", price_per_person: true,per_person:  30, price_event:  0, timeframe: 120, hints: "Go past the junk"})
Adventure.create({name: "Mulberry Project" ,location: "ChIJGaAyS4hZwokRzKiuS8sNU0A", price_per_person: true,per_person: 30 , price_event: 0, timeframe: 120, hints: "Behind the red door"})
Adventure.create({name: "Bar Centrale" ,location: "ChIJ4e2I9lNYwokRaO-Ake7hsak", price_per_person: true,per_person:  30, price_event: 0, timeframe: 120 , hints: "324"})
Adventure.create({name: "Attaboy" ,location: "ChIJxUZzBIdZwokRWA8buz-Nktc", price_per_person: true,per_person:  30, price_event: 0, timeframe: 120, hints: "134"})
Adventure.create({name: "Bathtub Gin" ,location: "ChIJcTnRKLlZwokRT8ZXt9W9cgw", price_per_person: true,per_person: 30 , price_event: 0, timeframe: 120, hints: "Behind Stone Street Coffee"})
Adventure.create({name: "Apotheke" ,location: "ChIJNxEu8SZawokRARkMLjXhyBY", price_per_person: true ,per_person: 30 , price_event: 0, timeframe: 120, hints: "The Chemist"})
Adventure.create({name: "Little Branch" ,location: "ChIJjY7y6ZJZwokRXF5CA_X4l-I", price_per_person: true ,per_person: 30 , price_event: 0, timeframe: 120, hints: "Talk to the man on the corner"})
Adventure.create({name: "Old Rabbit Club" ,location: "ChIJsU0rhJFZwokRmUJmeDamSLo", price_per_person: true ,per_person:  30, price_event: 0, timeframe: 120, hints: "Follow the yellow rabbit"})
Adventure.create({name: "Morbid Anatomy Museum" ,location: "ChIJRRCONVRawokRUHEzv2hWkus", price_per_person: true ,per_person:  8, price_event: 0, timeframe: 120, hints: "Morbid Anatomy Museum"})
Adventure.create({name: "Wave Hill" ,location: "ChIJC21UnrXzwokRn8wMoHqA8tw", price_per_person: true ,per_person:  8, price_event: 0, timeframe:160 , hints: "Garden"})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})
Adventure.create({name: "" ,location: "", price_per_person: ,per_person:  , price_event: , timeframe: , hints: ""})




User.create({name: "Matt", email: "Matt@wingit.com", password: "password"})
User.create({name: "Sam", email: "Sam@wingit.com", password: "password"})
User.create({name: "Ethan", email: "Ethan@wingit.com", password: "password"})
User.create({name: "David", email: "David@wingit.com", password: "password"})



User.create({name: "Matt", email: "Matt@wingit.com", password: "password"})
User.create({name: "Sam", email: "Sam@wingit.com", password: "password"})
User.create({name: "Ethan", email: "Ethan@wingit.com", password: "password"})
User.create({name: "David", email: "David@wingit.com", password: "password"})